# Generated by Django 5.2.6 on 2025-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_featuredbike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='features/')),
                ('number', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
