# Generated by Django 5.2.6 on 2025-09-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_testimonialsection_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rider_stories/')),
            ],
        ),
    ]
