# Generated by Django 5.2.6 on 2025-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_embed_url',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_image',
            field=models.ImageField(blank=True, help_text='Upload map image instead of Google embed', null=True, upload_to='contact_maps/'),
        ),
    ]
