# Generated by Django 5.2.6 on 2025-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0013_remove_contactinfo_map_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('scooter', 'Scooter'), ('sports', 'Sports'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('km_driven', models.PositiveIntegerField()),
                ('engine_cc', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('diesel', 'Diesel')], max_length=20)),
                ('color', models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('white', 'White')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='bikes/')),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
