# Generated by Django 5.2.6 on 2025-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0014_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
