# Generated by Django 5.2.6 on 2025-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0015_bike_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bike',
            name='pdated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
