# Generated by Django 5.2.6 on 2025-09-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0016_remove_bike_updated_at_bike_pdated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
