# Generated by Django 5.2.6 on 2025-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0017_filteroption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterOption',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='pdated_at',
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='engine_cc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='km_driven',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(),
        ),
    ]
