# Generated by Django 5.2.6 on 2025-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0018_delete_filteroption_remove_bike_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='booking_steps/')),
            ],
        ),
    ]
