# Generated by Django 5.2.6 on 2025-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0019_bikebookingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sellbanners/')),
            ],
        ),
    ]
