# Generated by Django 5.2.6 on 2025-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0020_sellbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellbikeCalculatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='calculator_bg/')),
                ('title', models.CharField(default='Get Your Bike Price', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='sellbanner',
            name='image',
            field=models.ImageField(upload_to='sell_banners/'),
        ),
    ]
