# Generated by Django 5.2.6 on 2025-09-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0021_sellbikecalculatorsection_alter_sellbanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbikecalculatorsection',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
