# Generated by Django 5.2.6 on 2025-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0023_howitworks_howitworkssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='how_it_works/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HowItWorks',
        ),
        migrations.RemoveField(
            model_name='howitworkssection',
            name='background_image',
        ),
        migrations.AlterField(
            model_name='howitworkssection',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='howitworkssection',
            name='section_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='howitworkssection',
            name='cards',
            field=models.ManyToManyField(to='bikes.howitworkscard'),
        ),
    ]
